//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RManager.Models
{
    using System;
    
    public partial class Adress
    {
        public string Country { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public string Bilding { get; set; }
        public string Index { get; set; }
    }
}
