//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Branch()
        {
            this.Adress = new Adress();
            this.Characters = new Characters();
        }
    
        public int Id { get; set; }
        public string WebSite { get; set; }
        public string Phone { get; set; }
        public Nullable<System.TimeSpan> StartWorkingTime { get; set; }
        public Nullable<System.TimeSpan> EndWorkingTime { get; set; }
        public Nullable<System.DateTime> InspectionDate { get; set; }
        public Nullable<double> FactualCashbox { get; set; }
    
        public Adress Adress { get; set; }
        public Characters Characters { get; set; }
    
        public virtual CompanyOwner Owner { get; set; }
        public virtual Landlord Landlord { get; set; }
    }
}
