//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckDish
    {
        public int Id { get; set; }
        public bool IsPaid { get; set; }
        public System.DateTime AddDateTime { get; set; }
        public Nullable<System.DateTime> PaidDateTime { get; set; }
        public Nullable<decimal> FinalPrice { get; set; }
    
        public virtual Dish Dish { get; set; }
        public virtual Order Order { get; set; }
    }
}
