//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee : Person
    {
        public string Login { get; set; }
        public string Password { get; set; }
        public bool IsWorking { get; set; }
        public string Description { get; set; }
    
        public virtual Position Position { get; set; }
        public virtual Branch Branch { get; set; }
    }
}
