//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RManager.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelContainer : DbContext
    {
        public ModelContainer()
            : base("name=ModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Document> Document { get; set; }
        public virtual DbSet<Position> Position { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<Dish> Dish { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<Purchase> Purchase { get; set; }
        public virtual DbSet<Ejection> Ejection { get; set; }
        public virtual DbSet<CheckDish> CheckDish { get; set; }
        public virtual DbSet<Table> TableSet { get; set; }
        public virtual DbSet<RecipeDishIngr> RecipeDishIngr { get; set; }
        public virtual DbSet<Room> Room { get; set; }
        public virtual DbSet<Branch> Branch { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Person> Person { get; set; }
        public virtual DbSet<Company> Company { get; set; }
        public virtual DbSet<Prepack> PrepackSet { get; set; }
        public virtual DbSet<RecipePrepIngr> RecipePrepIngr { get; set; }
        public virtual DbSet<RecipeDishPrep> RecipeDishPrep { get; set; }
        public virtual DbSet<RecipePrepPrep> RecipePrepPrep { get; set; }
        public virtual DbSet<CheckMerchandise> CheckMerchandise { get; set; }
        public virtual DbSet<Shift> ShiftSet { get; set; }
        public virtual DbSet<Encashment> EncashmentSet { get; set; }
    }
}
