//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Position
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Position()
        {
            this.WorkWithOrders = false;
            this.WorkWithMenu = false;
            this.WorkWithWarehouse = false;
            this.WorkWithStuff = false;
            this.WorkWithReports = false;
            this.WorkWithTables = false;
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public bool WorkWithOrders { get; set; }
        public bool WorkWithMenu { get; set; }
        public bool WorkWithWarehouse { get; set; }
        public bool WorkWithStuff { get; set; }
        public bool WorkWithReports { get; set; }
        public bool WorkWithTables { get; set; }
    }
}
