//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Property { get; set; }
        public Measure Measure { get; set; }
        public Nullable<bool> IsIngredient { get; set; }
        public bool IsMerchandise { get; set; }
        public Nullable<System.DateTime> InspectionDate { get; set; }
        public Nullable<double> FactualNumber { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Company Manufacturer { get; set; }
    }
}
