//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shift
    {
        public int Id { get; set; }
        public Nullable<System.TimeSpan> StartDateTime { get; set; }
        public Nullable<System.TimeSpan> EndDateTime { get; set; }
        public decimal StartFactualCashbox { get; set; }
        public decimal EndFactualCash { get; set; }
        public decimal EndFactualNonCash { get; set; }
    
        public virtual Employee Person { get; set; }
        public virtual Branch Branch { get; set; }
    }
}
